### ISSUE TITLE
Themes not displaying properly

### ISSUE THREAD

**Issue by gless** [plashenkov/TBX#9]
Hi,

Does TBX use the VCL styles available in XE8? I tried changing the Appearance of the application to "Metropolis UI Green" and the TBX menus and buttons styles did not change?

Thanks,
Eric

**Comment by plashenkov** [comment]
Hello! Sorry for the late reply. GitHub did not notify me about issues for some reason.

Currently TBX does not support Metropolis UI. No plans for this in the near future.
